language: node_js

node_js:
    - "stable"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
    - npm test
    - kill $(jobs -p) || true
